
AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for EKS cluster and control plane

Resources: 
  EKSRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - eks.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

Outputs:
  EKSRoleArn:
    Description: Role arn for Amazon EKS and the Kubernetes control plane to manage AWS resources
    Value: !GetAtt EKSRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}:EKSRoleArn
